apiVersion: skaffold/v4beta3
kind: Config
manifests:
  kustomize:
    paths:
      - ./k8s/base # skaffold uses kustomize to build the base yaml files, which should be configured to run locally
build:
  local:
    push: false
  artifacts:
    - image: kazuku/kazuku-admin-api
      context: admin-api  # the folder to look in for the Dockerfile and the sync below
      docker:
        dockerfile: Dockerfile.dev
        noCache: true
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.json'
            dest: .

