FROM node:20.15.1-bookworm-slim

EXPOSE 3000
USER node
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY --chown=node:node . .

CMD ["npm", "start"]
