name: deploy-k8s-manifests

on:
  push:
    branches:
      - dev
    paths:
      - 'k8s/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          project_id: 'kazuku'
          workload_identity_provider: 'projects/297600345242/locations/global/workloadIdentityPools/github/providers/kazuku'

      - name: Get GKE credentials
        id: 'get-credentials'
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: 'kazuku-preprod'
          location: 'us-central1'
          credentials: ${{ steps.auth.outputs.credentials }}

      - name: Apply k8s manifests in GCP
        run: kubectl apply -f k8s
